spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop
medrag:
  security:
    private-key-path: src/test/resources/test-private.pem
    public-key-path: src/test/resources/test-public.pem
