global:
  scrape_interval: 15s
scrape_configs:
  - job_name: medrag-api
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["api:9091"]
  - job_name: medrag-ai
    metrics_path: /metrics
    static_configs:
      - targets: ["ai:8000"]
